.TH vimpc 1 "November 2010" "" ""
.SH NAME
vimpc \- vi inspired Music Player Daemon (MPD) client.
.SH SYNOPSIS
.B vimpc [options]
.SH DESCRIPTION
.B vimpc 
provides simple access to 
.BR mpd (1)
via a familiar vi style interface
.SH OPTIONS
.IP --version
Print the version of vimpc
.SH FILES
.I ~/.vimpcrc
.RS
Per user configuration file. Executes the contents as vimpc commands.
.SH BUGS
Bugs should be reported on the vimpc trac http://sourceforge.net/apps/trac/vimpc/
.SH AUTHOR
Nathan Sweetman <nathan.sweetman@gmail.com>
.SH "SEE ALSO"
.BR mpd (1),
.BR mpc (1)
