.TH vimpc 1 "November 2010" "" ""
.SH NAME
vimpc \- vi inspired Music Player Daemon (MPD) client.
.SH SYNOPSIS
.B vimpc [options]
.SH DESCRIPTION
.B vimpc 
provides simple access to 
.BR mpd (1)
via a familiar vi style interface.

For detailed help information please type :help in vimpc.
.SH OPTIONS
.IP "-v, --version"
Print the version of vimpc
.IP "-h, --host [password@]<hostname|socket>"
Connect to a running MPD instance on
.BR hostname
or using the unix socket
.BR socket
with the password
.BR password
.IP "-p, --port <port>"
Use
.BR port
to connect to mpd
.SH ENVIRONMENT VARIABLES
All environment variables are overridden by options specified on the command line
.IP MPD_HOST
Specifies the host to connect to.
.IP MPD_PORT
Specifies the port to connect to.
.SH FILES
.I ~/.vimpcrc
.RS
Per user configuration file. Executes the contents as vimpc commands.
.SH BUGS
Bugs should be reported on github at http://github.com/boysetsfrog/vimpc/
.SH AUTHOR
Nathan Sweetman <nathan.sweetman@gmail.com>
.SH "SEE ALSO"
.BR mpd (1),
.BR mpc (1)
